FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the app code
COPY app.py .

# Expose the port used by the Python app
EXPOSE 5000

# Run the Python app
CMD ["python", "app.py"]
